name: askarie
description: A new Flutter application.
version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  url_launcher: ^5.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  step_progress_indicator: ^0.2.3+6
  shared_preferences: ^0.5.8
  cupertino_icons: ^0.1.2
  wc_flutter_share: ^0.2.1
  auto_size_text: ^2.1.0
  flutter_flexible_toast: ^0.1.4
  admob_flutter: "^0.3.4"
  firebase_admob: ^0.9.3+4
  loading_animations: ^2.1.0
  font_awesome_flutter: ^8.8.1
  dio: ^3.0.10
  week_of_year: ^1.0.1
  sqflite: ^1.3.1+1
  flutter_colored_progress_indicators: ^1.2.0
  load_toast: ^2.0.0+1
  loading_overlay: ^0.2.1
  fluttertoast: ^7.1.1
  auto_direction: ^0.0.4+1
  kt_dart: ^0.7.0+1
  connectivity: ^0.4.9+3
  percent_indicator: "^2.1.5"
  roundcheckbox: ^1.0.0+1
  avatar_glow: ^1.2.0
  firebase_messaging: any
  flutter_awesome_alert_box: ^1.0.1
  flutter_toggle_tab: ^0.0.3+2
  fialogs: ^1.1.3
  select_dialog: ^1.2.1
  introduction_screen: ^1.0.9






dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: ArbFONTS-Asmaa
      fonts:
        - asset: font/ArbFONTS-Asmaa-Font.otf
    - family: samat
      fonts:
        - asset: font/ArbFONTS-arbfonts-samt-7017.ttf