name: askarie
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  step_progress_indicator: ^0.2.3+6
  shared_preferences: ^0.5.8
  cupertino_icons: ^0.1.2
  wc_flutter_share: ^0.2.1
  auto_size_text: ^2.1.0
  flutter_flexible_toast: ^0.1.4
  admob_flutter: "^0.3.4"
  firebase_admob: ^0.9.3+4









dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: ArbFONTS-Asmaa
      fonts:
        - asset: font/ArbFONTS-Asmaa-Font.otf
    - family: samat
      fonts:
        - asset: font/ArbFONTS-arbfonts-samt-7017.ttf